name = "remix-guide"
type = "javascript"
workers_dev = false
account_id = "c63d756a160ad09cd9a82553c77e9174"
zone_id = "e433232c2f0e3fddcd03a20251740130"
route = "remix.guide/*"
compatibility_date = "2022-11-22"

[[kv_namespaces]]
binding = "CONTENT"
id = "f1a419c9f5524449b2c0562c7d774dd4"

[site]
bucket = "./public"
entry-point = "."

[durable_objects]
bindings = [
  { name = "RESOURCES_STORE", class_name = "ResourcesStore" },
  { name = "USER_STORE", class_name = "UserStore" },
  { name = "PAGE_STORE", class_name = "PageStore" },
]

[[migrations]]
tag = "v0.1"
new_classes = ["Counter"]

[[migrations]]
tag = "v1.0"
new_classes = ["ResourcesStore", "UserStore"]
deleted_classes = ["Counter"]

[[migrations]]
tag = "v1.1"
new_classes = ["PageStore"]

[build]
command = "npm run build"
watch_dir = "./build/index.js"

[build.upload]
format = "modules"
dir = "./dist"
main = "./worker.mjs"
